[package]
name = "socket_test"
version = "0.1.0"
authors = ["Batuhan ÃœNDAR <batuhan.undar@ulakhaberlesme.com.tr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
